export const initialState = {
  fullname: "",
  jobRole: "",
  tags: "",
  birthday: Date.now(),
  contract: Date.now(),
  health: 0,
  fitpass: 0,
  healthUsers: "",
  fitpassUsers: "",
  debtHealth: "",
  debtFitpass: "",
  eyes: Date.now(),
  safety: Date.now(),
  fire: Date.now(),
  firstAid: Date.now(),
  bankOne: "",
  bankTwo: "",
  selectedFile: "",
};
